using PricingAndTrading.Application.Orders.History;
using PricingAndTrading.Domain.Orders;
using PricingAndTrading.Infrastructure.Persistence.Repositories;

namespace PricingAndTrading.IntegrationTests.Persistence.PostgreSql;

[Collection(PostgreSqlCollection.Name)]
public sealed class PostgreSqlOrderHistoryTests(PostgreSqlFixture fixture)
{
    private static readonly DateTimeOffset Timestamp =
        new(2026, 9, 4, 9, 0, 0, TimeSpan.Zero);

    [PostgreSqlFact]
    public async Task GetAsync_FiltersAndRepeatedBusinessId_ReturnsMatchingRowsAndOrderedReasons()
    {
        await fixture.ResetDataAsync();
        var writeRepository = new PostgresOrderRepository(
            fixture.CreateDbContextFactory());
        var historyRepository = new PostgresOrderHistoryRepository(
            fixture.CreateDbContextFactory());
        Guid repeatedOrderId = Guid.NewGuid();

        await SaveAsync(
            writeRepository,
            CreateOrder(
                repeatedOrderId,
                "EURUSD",
                OrderSource.Api,
                Timestamp),
            TradeDecision.Accepted(repeatedOrderId));

        Order repeatedRejected = CreateOrder(
            repeatedOrderId,
            "EURUSD",
            OrderSource.AutoGenerated,
            Timestamp.AddMinutes(1));
        await SaveAsync(
            writeRepository,
            repeatedRejected,
            TradeDecision.Rejected(
                repeatedOrderId,
                new RejectionReason("FIRST", "First reason."),
                new RejectionReason("SECOND", "Second reason.")));

        Guid gbpOrderId = Guid.NewGuid();
        Order gbpRejected = CreateOrder(
            gbpOrderId,
            "GBPUSD",
            OrderSource.Api,
            Timestamp.AddMinutes(2));
        await SaveAsync(
            writeRepository,
            gbpRejected,
            TradeDecision.Rejected(
                gbpOrderId,
                new RejectionReason("ONLY", "Only reason.")));

        OrderHistoryPage symbolResult = await historyRepository.GetAsync(
            new OrderHistoryQuery(symbol: " eurusd "));
        OrderHistoryPage statusResult = await historyRepository.GetAsync(
            new OrderHistoryQuery(status: OrderStatus.Rejected));
        OrderHistoryPage sourceResult = await historyRepository.GetAsync(
            new OrderHistoryQuery(source: OrderSource.Api));
        OrderHistoryPage rangeResult = await historyRepository.GetAsync(
            new OrderHistoryQuery(
                from: Timestamp.AddMinutes(1),
                to: Timestamp.AddMinutes(1)));
        OrderHistoryPage combinedResult = await historyRepository.GetAsync(
            new OrderHistoryQuery(
                symbol: "EURUSD",
                status: OrderStatus.Rejected,
                source: OrderSource.AutoGenerated,
                from: Timestamp,
                to: Timestamp.AddMinutes(2)));

        Assert.Equal(2, symbolResult.TotalCount);
        Assert.All(symbolResult.Items, item => Assert.Equal(repeatedOrderId, item.OrderId));
        Assert.Equal(Timestamp.AddMinutes(1), symbolResult.Items[0].CreatedAt);
        Assert.Equal(Timestamp, symbolResult.Items[1].CreatedAt);
        Assert.Equal(2, statusResult.TotalCount);
        Assert.All(statusResult.Items, item => Assert.Equal(OrderStatus.Rejected, item.Status));
        Assert.Equal(2, sourceResult.TotalCount);
        Assert.All(sourceResult.Items, item => Assert.Equal(OrderSource.Api, item.Source));
        Assert.Equal(repeatedOrderId, Assert.Single(rangeResult.Items).OrderId);

        OrderHistoryItem combinedItem = Assert.Single(combinedResult.Items);
        Assert.Equal(repeatedOrderId, combinedItem.OrderId);
        Assert.Collection(
            combinedItem.RejectionReasons,
            reason => Assert.Equal("FIRST", reason.Code),
            reason => Assert.Equal("SECOND", reason.Code));
    }

    [PostgreSqlFact]
    public async Task GetAsync_PageTwo_ReturnsNewestFirstPageAndTotalCount()
    {
        await fixture.ResetDataAsync();
        var writeRepository = new PostgresOrderRepository(
            fixture.CreateDbContextFactory());
        var historyRepository = new PostgresOrderHistoryRepository(
            fixture.CreateDbContextFactory());

        for (var index = 0; index < 5; index++)
        {
            Guid orderId = Guid.NewGuid();
            await SaveAsync(
                writeRepository,
                CreateOrder(
                    orderId,
                    "EURUSD",
                    OrderSource.Api,
                    Timestamp.AddMinutes(index)),
                TradeDecision.Accepted(orderId));
        }

        OrderHistoryPage result = await historyRepository.GetAsync(
            new OrderHistoryQuery(page: 2, pageSize: 2));

        Assert.Equal(5, result.TotalCount);
        Assert.Equal(2, result.Page);
        Assert.Equal(2, result.PageSize);
        Assert.Collection(
            result.Items,
            item => Assert.Equal(Timestamp.AddMinutes(2), item.CreatedAt),
            item => Assert.Equal(Timestamp.AddMinutes(1), item.CreatedAt));
    }

    private static Order CreateOrder(
        Guid orderId,
        string symbol,
        OrderSource source,
        DateTimeOffset createdAt) =>
        new(
            orderId,
            symbol,
            OrderSide.Buy,
            OrderType.Limit,
            100m,
            5m,
            source,
            createdAt);

    private static Task SaveAsync(
        PostgresOrderRepository repository,
        Order order,
        TradeDecision decision) =>
        repository.SaveAsync(order, decision, CancellationToken.None);
}
