// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PricingAndTrading.Infrastructure.Persistence;

#nullable disable

namespace PricingAndTrading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.LatestPriceEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("AskPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("BidPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("SpreadPercent")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Symbol");

                    b.ToTable("LatestPrices", (string)null);
                });

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Symbol", "CreatedAt");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.OrderIdRegistrationEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.ToTable("OrderIdRegistrations", (string)null);
                });

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.OrderRejectionReasonEntity", b =>
                {
                    b.Property<Guid>("OrderPersistenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("OrderPersistenceId", "Sequence");

                    b.ToTable("OrderRejectionReasons", (string)null);
                });

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.TradingRulesEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("AutoTradingSpreadThresholdPercent")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<bool>("DuplicateOrderIdCheckEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaximumNotionalAmount")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("MaximumPriceDeviationPercent")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.Property<decimal>("MaximumQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)");

                    b.PrimitiveCollection<string[]>("SymbolWhitelist")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("SymbolWhitelistEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TradingRules", (string)null);
                });

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.OrderRejectionReasonEntity", b =>
                {
                    b.HasOne("PricingAndTrading.Infrastructure.Persistence.Entities.OrderEntity", "Order")
                        .WithMany("RejectionReasons")
                        .HasForeignKey("OrderPersistenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PricingAndTrading.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Navigation("RejectionReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
