using PricingAndTrading.Application.AutoTrading;
using PricingAndTrading.Domain.Orders;
using PricingAndTrading.Domain.Prices;
using TradingRulesConfiguration = PricingAndTrading.Domain.TradingRules.TradingRules;

namespace PricingAndTrading.UnitTests.AutoTrading;

public sealed class AutoTradingEngineTests
{
    private static readonly DateTimeOffset Timestamp =
        new(2026, 9, 3, 15, 30, 0, TimeSpan.Zero);

    private readonly AutoTradingEngine _engine = new();

    [Fact]
    public void Evaluate_NoPreviousPrice_ReturnsNoOrder()
    {
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Order? order = _engine.Evaluate(null, current, CreateTradingRules(1m));

        Assert.Null(order);
    }

    [Fact]
    public void Evaluate_SpreadBelowThreshold_ReturnsNoOrder()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Order? order = _engine.Evaluate(previous, current, CreateTradingRules(2m));

        Assert.Null(order);
    }

    [Fact]
    public void Evaluate_SpreadEqualToThreshold_ReturnsNoOrder()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);
        TradingRulesConfiguration rules = CreateTradingRules(current.SpreadPercent);

        Order? order = _engine.Evaluate(previous, current, rules);

        Assert.Null(order);
    }

    [Fact]
    public void Evaluate_SpreadAboveThreshold_ReturnsOrder()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Order? order = _engine.Evaluate(previous, current, CreateTradingRules(1m));

        Assert.NotNull(order);
    }

    [Fact]
    public void Evaluate_CurrentMarketPriceIncreased_ReturnsSellOrder()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, CreateTradingRules(0m)));

        Assert.Equal(OrderSide.Sell, order.Side);
    }

    [Fact]
    public void Evaluate_CurrentMarketPriceDecreased_ReturnsBuyOrder()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 102m, 104m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, CreateTradingRules(0m)));

        Assert.Equal(OrderSide.Buy, order.Side);
    }

    [Fact]
    public void Evaluate_CurrentMarketPriceEqualsPrevious_ReturnsNoOrder()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("EURUSD", 98m, 102m);

        Order? order = _engine.Evaluate(previous, current, CreateTradingRules(0m));

        Assert.Null(order);
    }

    [Fact]
    public void Evaluate_SellSignal_AdjustsAskPriceByPointZeroThreePercentWithoutRounding()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 98m, 100m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100.123456789m, 101.123456789m);
        decimal expectedPrice = current.AskPrice - (current.AskPrice * 0.0003m);

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, CreateTradingRules(0m)));

        Assert.Equal(expectedPrice, order.Price);
        Assert.NotEqual(decimal.Round(expectedPrice, 4), order.Price);
    }

    [Fact]
    public void Evaluate_BuySignal_AdjustsBidPriceByPointZeroThreePercent()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 102m, 104m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);
        decimal expectedPrice = current.BidPrice + (current.BidPrice * 0.0003m);

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, CreateTradingRules(0m)));

        Assert.Equal(expectedPrice, order.Price);
    }

    [Fact]
    public void Evaluate_EligiblePriceMove_CreatesAutoGeneratedLimitOrderWithCurrentContext()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, CreateTradingRules(0m)));

        Assert.NotEqual(Guid.Empty, order.Id);
        Assert.Equal(current.Symbol, order.Symbol);
        Assert.Equal(OrderType.Limit, order.Type);
        Assert.Equal(OrderSource.AutoGenerated, order.Source);
        Assert.Equal(current.Timestamp, order.CreatedAt);
    }

    [Fact]
    public void Evaluate_NotionalIsLimitingFactor_UsesTenPercentTargetNotional()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 102m, 104m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);
        TradingRulesConfiguration rules = CreateTradingRules(
            threshold: 0m,
            maximumNotionalAmount: 100_030m,
            maximumQuantity: 2_000m);
        decimal targetNotional = rules.MaximumNotionalAmount * 0.10m;

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, rules));

        Assert.Equal(targetNotional / order.Price, order.Quantity);
        Assert.True(order.Quantity > 0m);
        Assert.True(order.Price * order.Quantity <= targetNotional);
    }

    [Fact]
    public void Evaluate_QuantityCapIsLimitingFactor_UsesTenPercentMaximumQuantity()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 102m, 104m);
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);
        TradingRulesConfiguration rules = CreateTradingRules(
            threshold: 0m,
            maximumNotionalAmount: 1_000_000m,
            maximumQuantity: 50m);

        Order order = Assert.IsType<Order>(
            _engine.Evaluate(previous, current, rules));

        Assert.Equal(rules.MaximumQuantity * 0.10m, order.Quantity);
        Assert.True(order.Quantity > 0m);
        Assert.True(
            order.Price * order.Quantity <=
            rules.MaximumNotionalAmount * 0.10m);
    }

    [Fact]
    public void Evaluate_MismatchedSymbols_ThrowsArgumentException()
    {
        MarketPrice previous = CreateMarketPrice("EURUSD", 99m, 101m);
        MarketPrice current = CreateMarketPrice("GBPUSD", 100m, 102m);

        Assert.Throws<ArgumentException>(() =>
            _engine.Evaluate(previous, current, CreateTradingRules(0m)));
    }

    [Fact]
    public void Evaluate_NullCurrentPrice_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() =>
            _engine.Evaluate(null, null!, CreateTradingRules(0m)));
    }

    [Fact]
    public void Evaluate_NullTradingRules_ThrowsArgumentNullException()
    {
        MarketPrice current = CreateMarketPrice("EURUSD", 100m, 102m);

        Assert.Throws<ArgumentNullException>(() =>
            _engine.Evaluate(null, current, null!));
    }

    private static MarketPrice CreateMarketPrice(
        string symbol,
        decimal bidPrice,
        decimal askPrice) =>
        MarketPrice.From(new PriceTick(symbol, bidPrice, askPrice, Timestamp));

    private static TradingRulesConfiguration CreateTradingRules(
        decimal threshold,
        decimal maximumNotionalAmount = 100_000m,
        decimal maximumQuantity = 1_000m) =>
        new(
            maximumNotionalAmount,
            maximumQuantity,
            duplicateOrderIdCheckEnabled: true,
            symbolWhitelistEnabled: false,
            symbolWhitelist: null,
            autoTradingSpreadThresholdPercent: threshold);
}
