using PricingAndTrading.Domain.Orders;
using PricingAndTrading.Domain.Prices;
using TradingRulesConfiguration = PricingAndTrading.Domain.TradingRules.TradingRules;

namespace PricingAndTrading.Application.AutoTrading;

public sealed class AutoTradingEngine : IAutoTradingEngine
{
    private const decimal PriceAdjustment = 0.0003m;
    private const decimal OrderSizingFactor = 0.10m;

    public Order? Evaluate(
        MarketPrice? previous,
        MarketPrice current,
        TradingRulesConfiguration tradingRules)
    {
        ArgumentNullException.ThrowIfNull(current);
        ArgumentNullException.ThrowIfNull(tradingRules);

        if (previous is null)
        {
            return null;
        }

        if (!string.Equals(previous.Symbol, current.Symbol, StringComparison.Ordinal))
        {
            throw new ArgumentException(
                "Previous and current market prices must have the same symbol.",
                nameof(previous));
        }

        if (current.SpreadPercent <= tradingRules.AutoTradingSpreadThresholdPercent)
        {
            return null;
        }

        int marketPriceComparison = current.CurrentMarketPrice.CompareTo(
            previous.CurrentMarketPrice);

        if (marketPriceComparison == 0)
        {
            return null;
        }

        OrderSide side = marketPriceComparison > 0
            ? OrderSide.Sell
            : OrderSide.Buy;

        decimal orderPrice = side == OrderSide.Sell
            ? current.AskPrice - (current.AskPrice * PriceAdjustment)
            : current.BidPrice + (current.BidPrice * PriceAdjustment);

        decimal targetNotional = tradingRules.MaximumNotionalAmount * OrderSizingFactor;
        decimal quantityByNotional = targetNotional / orderPrice;
        decimal quantityCap = tradingRules.MaximumQuantity * OrderSizingFactor;
        decimal quantity = Math.Min(quantityByNotional, quantityCap);

        return new Order(
            Guid.NewGuid(),
            current.Symbol,
            side,
            OrderType.Limit,
            orderPrice,
            quantity,
            OrderSource.AutoGenerated,
            current.Timestamp);
    }
}
